name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '52 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch pollen data
      run: |-
        bash pollen.sh > pollen.json
    - name: Fetch 3day data
      run: |-
        bash wu_3day.sh > wu_3day.json
    - name: Fetch 7day data
      run: |-
        bash wu_7day.sh > wu_7day.json
    - name: Fetch aqi data
      run: |-
        bash wu_aqi.sh > wu_aqi.json
    - name: Fetch aqi2 data
      run: |-
        bash wu_aqi2.sh > wu_aqi2.json
    - name: Fetch current data
      run: |-
        bash wu_current.sh > wu_current.json
    - name: Fetch current2 data
      run: |-
        bash wu_current2.sh > wu_current2.json
    - name: Fetch pollen2 data
      run: |-
        bash wu_pollen.sh > wu_pollen.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
